require("configs.packer")
require("plugs.neo-nvim")
require("plugs.barbar")
require("plugs.coc-config")
require("plugs.floaterm")
require("plugs.codeium-conf")
require("plugs.tree-sitter-conf")
require("plugs.lualine-conf")
require("plugs.alpha-config")
require("plugs.color-theme")

